### ISSUE TITLE
Feature #1: User can add new recipes.

### ISSUE THREAD

**Issue by ry-zhao** [ry-zhao/ajax-project#1]
## 💰 Motivation

Users will want to add new recipes.

## 📐 Plan

Create a form that allows user to add new recipes, specifying title, photo URL, ingredients, and instructions.

## 🖼️ Wireframes

![Screenshot 2021-09-21 163820](https://user-images.githubusercontent.com/88162193/134261417-1d0e8a4e-b30d-4a32-bce3-ba2369002f5f.png)
![Screenshot 2021-09-21 163904](https://user-images.githubusercontent.com/88162193/134261467-107a70c2-c8eb-4963-a3a0-6f479d8d8ddd.png)

## ✅ Task List

- [x] Create view containing recipe form
- [x] Create title element
- [x] Create image element
- [x] Create unordered list representing ingredients
- [x] Create unordered list representing instructions
- [x] Create data object stored in localStorage
- [x] Add array to data named recipes
- [x] Create data model representing current recipe
- [x] Add event listener to title input that fires upon user input an updates title element to correspond with input value
- [x] Add event listener to image URL input that fires upon user input and updates image element's src attribute to correspond with input value
- [x] Add event listener to add ingredient button that fires upon click and updates the list to include the value of the add ingredient input
- [x] Add event listener to add instruction button that fires upon click and updates the list to include the value of the add instruction input
- [x] Add event listener to the save button that fires when clicked and queries the title, image URL, ingredients, and instructions and uses the values to update the recipe data model and push it to data.recipes
- [x] Make desktop compatible
