### ISSUE TITLE
Feature #2: User can view their saved recipes

### ISSUE THREAD

**Issue by ry-zhao** [ry-zhao/ajax-project#2]
## 💰 Motivation

Users will want to add new recipes.

## 📐 Plan

Create a form that allows user to add new recipes, specifying title, photo URL, ingredients, and instructions.

## 🖼️ Wireframes
https://www.figma.com/file/kUx2lGUJtiX8SCZ0N56vHj/Ryan-Zhao---AJAX-Project?node-id=1%3A3

## ✅ Task List

- [x] Create new view that displays recipes saved by the user.
  - [x] Create function that populates recipes view with cards of all saved recipes.
- [x] Add event listener to recipe cards so that when clicked the page switches from the recipes to read view.
- [x] Format new view that displays the recipe in detail (includes instructions).
- [x] Add event listener to book icon in header that leads back to the recipes view when clicked.
- [x] Make desktop compatible.
