### ISSUE TITLE
Feature #4: User can search for new recipes with API

### ISSUE THREAD

**Issue by ry-zhao** [ry-zhao/ajax-project#4]
## 💰 Motivation

Users will want to search for new recipes.

## 📐 Plan

Create a form that allows users to use API to search for new recipes.

## 🖼️ Wireframes

![Screenshot 2021-09-24 153324](https://user-images.githubusercontent.com/88162193/134746325-8b0849db-b215-48c2-8c8d-f0c9404e2059.png)
![Screenshot 2021-09-24 153250](https://user-images.githubusercontent.com/88162193/134746324-6b8d33e0-7381-4a68-a1f2-86dc947da6d9.png)

## ✅ Task List

- [x] Create new view for searches.
- [x] Create search form with search bar and button.
- [x] Add event listener to search form that sends appropriate XHR to spoonacular API when 'submit' event is fired.
- [x] Create function that populates search view with first 10 results when 'load' event fires.
- [x] Make desktop comptaible
- [x] Debug
