### ISSUE TITLE
Issue #5: User can copy and save recipes from API search.

### ISSUE THREAD

**Issue by ry-zhao** [ry-zhao/ajax-project#5]
## 💰 Motivation

User will want to copy and save recipes from API.

## 📐 Plan

Add copy button that automatically populates new recipe form with specified recipe.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/88162193/135536117-d3c7d3c1-d3f6-4092-9d23-b1c71e333413.png)
![image](https://user-images.githubusercontent.com/88162193/135661688-ca8cbe1c-146c-4eb7-83f5-8435fe3d9024.png)
![image](https://user-images.githubusercontent.com/88162193/135535337-570bb798-efa8-4f51-8614-7765dcfb5530.png)

## ✅ Task List

- [x] Swap to detailed recipe view when info anchor on recipe search results are clicked.
- [x] Add "COPY RECIPE" button to detailed recipe view while viewing recipes from search list.
- [x] Add event listener so that when "COPY RECIPE" button is clicked, the app swaps to new recipe view.
  - [x] Populate new recipe view with title, image, ingredients, and instructions of said recipe.
